"""Creating first Migration

Revision ID: cc970fd452f9
Revises: 83caf53024bf
Create Date: 2020-08-23 13:18:44.742827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc970fd452f9'
down_revision = '83caf53024bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.add_column('bridges', sa.Column('water_level_threshold_alert', sa.Float(), nullable=True))
    op.add_column('bridges', sa.Column('water_level_threshold_monitor', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bridges', 'water_level_threshold_monitor')
    op.drop_column('bridges', 'water_level_threshold_alert')
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name='PK__migrate___5D3A00248BDB65CB')
    )
    # ### end Alembic commands ###
